console.dir(document.querySelector("p" ))
console.dir(document.querySelector("h1"))
console.dir(document.querySelector("div a"))
console.dir(console.log("for all "))
console.dir(document.querySelectorAll("p"))
let a = document.querySelectorAll("div a")
console.dir(a[0])
